export const highlightList = [
  "TIKINGON",
  "Giày thể thao nam",
  "Balo",
  "Máy Bay Camera - Drone",
  "Điện thoại Smartphone",
  "Sách tư duy - Kỹ năng sống",
  "Tiểu Thuyết",
  "Loa Bluetooth",
  "Truyện Tranh, Manga, Comic",
  "Nồi chiên",
  "Truyện ngắn - Tản văn - Tạp Văn",
  "Camera IP",
  "Bài học kinh doanh",
  "Nước ngọt",
  "Bia Nội Địa",
  "Tủ",
  "Sách nghệ thuật sống đẹp",
  "Tai Nghe True Wireless",
  "Đồng Hồ Thông Minh",
  "Tủ lạnh",
];
