export const plainTextCatelory = [
  'Thịt, Rau Củ',
  'Bách Hóa',
  'Nhà Cửa',
  'Điện Tử',
  'Thiết bị số',
  'Điện thoại',
  'Mẹ & Bé',
  'Làm Đẹp',
  'Gia Dụng',
  'Thời Trang Nam',
  'Thời Trang Nữ',
  'Giày Nữ',
  'Túi Nữ',
  'Giày Nam',
  'Túi Nam',
  'Balo & Vali',
  'Phụ Kiện',
  'Đồng Hồ',
  'Laptop',
  'Quốc Tế',
  'Voucher',
  'Xe',
  'Sách',
  'Thể Thao',
  'Máy ảnh',
]